// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkduGBmOARo5OEzbDEzlRUlxanvjgMIQ0',
    appId: '1:482740150360:web:3c4967e22eb07dadda2a2d',
    messagingSenderId: '482740150360',
    projectId: 'chatex-1781c',
    authDomain: 'chatex-1781c.firebaseapp.com',
    storageBucket: 'chatex-1781c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtPH7alsBQpxbcUbsqrk0On1B7tWJxQ7U',
    appId: '1:482740150360:android:712a8bb6782b16f7da2a2d',
    messagingSenderId: '482740150360',
    projectId: 'chatex-1781c',
    storageBucket: 'chatex-1781c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkduGBmOARo5OEzbDEzlRUlxanvjgMIQ0',
    appId: '1:482740150360:web:e13f9771591b48efda2a2d',
    messagingSenderId: '482740150360',
    projectId: 'chatex-1781c',
    authDomain: 'chatex-1781c.firebaseapp.com',
    storageBucket: 'chatex-1781c.firebasestorage.app',
  );
}
